---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    env_file: .env # use .env file
    environment:
      PUID: $PUID # optional, your user id
      PGID: $PGID # optional, your group id
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
     # - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped