---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: Steves Notebook Homepage

background: 
 image: https://images.unsplash.com/photo-1563089145-599997674d42?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
 blur: sm
 opacity: 66 
 brightness: 100
 saturate: 100

theme: dark
color: slate

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
